### ISSUE TITLE
Clicking on last move of Game record produces empty game list (below)

### ISSUE THREAD

**Issue by gbtami** [sshivaji/chessui#1]

**Comment by sshivaji** [comment]
That is to be expected because there are no games from the last move of that game. However, should it display "No games found" instead?

**Comment by gbtami** [comment]
If the game list (below) shows all games where the shown board (above) position occurs then I always expect at least the game I'm moving in "Game record" to be in the below list because _all_ positions are occurs in that game even the last one :)

**Comment by sshivaji** [comment]
It actually means that there are no further moves in chess_db for that fen.

This is almost a limitation with polyglot format. It gives stats by move
from a position, if no moves are played, it shows no results

**Comment by gbtami** [comment]
You are right. Sometimes I forget that scoutfish "sub-fen" search is not the same as chess-db "find". Sorry for nitpicking!
